### ISSUE TITLE
Configuration doesn't work

### ISSUE THREAD

**Issue by ghost** [Odonno/pomodoro-code#16]
@Odonno I tried 3 methods to change the timer from 25 minutes to 60 minutes: 
1. control+shift+p -> Configure Pomodoro , nothing shows up.
2. create manually the config.json inside .vscode folder, copy-paste the values and change them, restart visual studio code, didn't worked.
3. create manually the config.json inside the current working folder, copy-paste the values and change them, restart visual studio code, didn't worked.

How can I configure the timer? 5x25minutes is too low, maybe it's better to move the pomodoro's configuration inside the user's config (./vscode/settings.json) ?

**Comment by Odonno** [comment]
@kataras It should be fixed now (v0.2.1).

I am now using the global `settings.json` file (user settings). You can edit this file using `Configure Pomodoro` command or editing directly the file from its location based on your OS (https://code.visualstudio.com/docs/customization/userandworkspace#_settings-file-locations).

Thanks for your feedback.

**Comment by ghost** [comment]
Ok so I will just add this on vs code's settings? 

```
    "pomodori": [
        {
            "work": 25,
            "pause": 5  
        },
        {
            "work": 25,
            "pause": 5  
        },
        {
            "work": 25,
            "pause": 5  
        },
        {
            "work": 25,
            "pause": 5  
        }
    ]

```

**Comment by Odonno** [comment]
@kataras There should be a sample on the readme.md file of the repo. But, yes, if you want 4 pomodori of 25/5, you should do that.

I already tested it on Windows 10 and it works. It should work the exact same way on Linux and Mac.

**Comment by ghost** [comment]
@Odonno  Okay, thanks you :)
