### ISSUE TITLE
Improve gallery banner

### ISSUE THREAD

**Issue by Odonno** [Odonno/pomodoro-code#3]
Create an image for the project visible here https://marketplace.visualstudio.com/items/odonno.pomodoro-code

**Comment by Odonno** [comment]
@gep13 What do you think about that ? https://marketplace.visualstudio.com/items/odonno.pomodoro-code

Although, there is a lack on the marketplace (https://marketplace.visualstudio.com/vscode/Other) when the image color and bakground color is the same... (see https://github.com/Microsoft/vscode/issues/401)

**Comment by gep13** [comment]
Gallery banner is looking really good!  And yes, I agree with the suggestion that you made to include the background colour in the marketplace! :+1:
