### ISSUE TITLE
Create GIF animation to show how to use the extension

### ISSUE THREAD

**Issue by Odonno** [Odonno/pomodoro-code#4]
Add a GIF to readme.MD file

**Comment by gep13** [comment]
You might want to give this a try:

http://www.cockos.com/licecap/

**Comment by Odonno** [comment]
Looks great !

**Comment by gep13** [comment]
Yip, seems to do the job :+1: The gif that I uploaded with the details of the screen refresh issue was created using it.

**Comment by Odonno** [comment]
Here it is. What do you think ?

![pomodoro-code](https://cloud.githubusercontent.com/assets/6053067/11303463/5f8a33aa-8fa3-11e5-9f41-2c8ed47b9446.gif)

**Comment by gep13** [comment]
Looks good to me :+1:
