### ISSUE TITLE
The timer seems to "jump" every second

### ISSUE THREAD

**Issue by gep13** [Odonno/pomodoro-code#6]
This is something that you can do anything about?

![pomodoro](https://cloud.githubusercontent.com/assets/1271146/11293836/b2f544ce-8f55-11e5-82fd-51bed8a8f475.gif)

**Comment by Odonno** [comment]
I don't know at this time. I have a done a very bad but effective refresh every second (using `setInterval`).
I'll read the docs in details for that. Is there anything to refresh UI (status bar item) easily ?

**Comment by gep13** [comment]
In all honesty, I am not sure, I haven't looked at the details of what you can/can't do within Code.

**Comment by Odonno** [comment]
@gep13 Seems to be fixed in 0.1.6 !

**Comment by gep13** [comment]
@Odonno looks good to me, just installed the latest version.  What was the fix?

**Comment by Odonno** [comment]
@gep13 I was executing show/hide each second, so it was a mistake. I replace by refreshign only when changing pomodoro status (work/pause/nothing).
