### ISSUE TITLE
Create a configuration file

### ISSUE THREAD

**Issue by Odonno** [Odonno/pomodoro-code#7]
Manage your own Pomodoro style using a `config.json` file. Don't know if it is possible at this time.

**Comment by Odonno** [comment]
@gep13 It's now available on 0.1.8 !

**Comment by gep13** [comment]
Nice one, I will check it out!  Where should I put that config.json file?

**Comment by Odonno** [comment]
It is already created when you install the extension.
To update the config, just use the command `configure pomodoro` (F1).

**Comment by gep13** [comment]
> @Odonno said...
> To update the config, just use the command configure pomodoro (F1).

Very cool!  Might be worth mentioning that in your readme.md file.

**Comment by Odonno** [comment]
I have an idea about that !
