### ISSUE TITLE
Change duration of timer

### ISSUE THREAD

**Issue by gep13** [Odonno/pomodoro-code#9]
Would it be possible to change the length of time of the pomodoro?  Although I think 25 minutes is the normal, I think it should be possible to configure this as well to your own liking.

**Comment by Odonno** [comment]
Are you refering to https://github.com/Odonno/pomodoro-code/issues/7 ?

Clearly, even without a config file, I don't know how to do it.

**Comment by gep13** [comment]
Ah yes, looks like we had the same idea :+1: 

From what I have seen, you might not get your own configuration file, but you might be able to reference a settings that you user puts into their user.json file, or the larger settings.json file (names recalled off the top of my head, so might be slightly different)
